version: '3'
services: 
    react-app: 
        build:
            dockerfile: Dockerfile.dev
            context: ./todoapp
        ports:
            - "3000:3000"
        volumes:
            - ./todoapp/src:/app/src
        links: 
            - node-app
        environment: 
            - SERVER_IP=node-app
    node-app:
        restart: always
        build: ./server
        ports:
            - "8000:8000"
        volumes: 
            - ./server:/app/
        links: 
            - mongo
        environment: 
            - MONGO_IP=mongo
    mongo:
        image: mongo
        ports:
            - "27017:27017"
